<h1>Identificador automático de idioma</h1>
<p><b>Problema</b>: Dados um texto de entrada, é possível identificar em qual língua o texto está escrito?</p>
<p>
Entrada: "texto qualquer" <br />
Saída: português ou inglês ou francês ou italiano ou...
</p>
<p>&nbsp;</p>

<h2>O processo de Reconhecimento de Padrões</h2>
<p>O objetivo desse trabalho é demonstrar o processo de "construção de atributos" e como ele é fundamental para o <b>Reconhecimento de Padrões (RP)</b>.</p>

<p>Primeiro um conjunto de "amostras" previamente conhecido (classificado)</p>

In [40]:
#
# amostras de texto em diferentes línguas
#
ingles = [
"Hello, how are you?",
"I love to read books.",
"The weather is nice today.",
"Where is the nearest restaurant?",
"What time is it?",
"I enjoy playing soccer.",
"Can you help me with this?",
"I'm going to the movies tonight.",
"This is a beautiful place.",
"I like listening to music.",
"Do you speak English?",
"What is your favorite color?",
"I'm learning to play the guitar.",
"Have a great day!",
"I need to buy some groceries.",
"Let's go for a walk.",
"How was your weekend?",
"I'm excited for the concert.",
"Could you pass me the salt, please?",
"I have a meeting at 2 PM.",
"I'm planning a vacation.",
"She sings beautifully.",
"The cat is sleeping.",
"I want to learn French.",
"I enjoy going to the beach.",
"Where can I find a taxi?",
"I'm sorry for the inconvenience.",
"I'm studying for my exams.",
"I like to cook dinner at home.",
"Do you have any recommendations for restaurants?",
]

espanhol = [
"Hola, ¿cómo estás?",
"Me encanta leer libros.",
"El clima está agradable hoy.",
"¿Dónde está el restaurante más cercano?",
"¿Qué hora es?",
"Voy al parque todos los días.",
"¿Puedes ayudarme con esto?",
"Me gustaría ir de vacaciones.",
"Este es mi libro favorito.",
"Me gusta bailar salsa.",
"¿Hablas español?",
"¿Cuál es tu comida favorita?",
"Estoy aprendiendo a tocar el piano.",
"¡Que tengas un buen día!",
"Necesito comprar algunas frutas.",
"Vamos a dar un paseo.",
"¿Cómo estuvo tu fin de semana?",
"Estoy emocionado por el concierto.",
"¿Me pasas la sal, por favor?",
"Tengo una reunión a las 2 PM.",
"Estoy planeando unas vacaciones.",
"Ella canta hermosamente.",
"El perro está jugando.",
"Quiero aprender italiano.",
"Disfruto ir a la playa.",
"¿Dónde puedo encontrar un taxi?",
"Lamento las molestias.",
"Estoy estudiando para mis exámenes.",
"Me gusta cocinar la cena en casa.",
"¿Tienes alguna recomendación de restaurantes?",
]

portugues = [
"Estou indo para o trabalho agora.",
"Adoro passar tempo com minha família.",
"Preciso comprar leite e pão.",
"Vamos ao cinema no sábado.",
"Gosto de praticar esportes ao ar livre.",
"O trânsito está terrível hoje.",
"A comida estava deliciosa!",
"Você já visitou o Rio de Janeiro?",
"Tenho uma reunião importante amanhã.",
"A festa começa às 20h.",
"Estou cansado depois de um longo dia de trabalho.",
"Vamos fazer um churrasco no final de semana.",
"O livro que estou lendo é muito interessante.",
"Estou aprendendo a cozinhar pratos novos.",
"Preciso fazer exercícios físicos regularmente.",
"Vou viajar para o exterior nas férias.",
"Você gosta de dançar?",
"Hoje é meu aniversário!",
"Gosto de ouvir música clássica.",
"Estou estudando para o vestibular.",
"Meu time de futebol favorito ganhou o jogo.",
"Quero aprender a tocar violão.",
"Vamos fazer uma viagem de carro.",
"O parque fica cheio aos finais de semana.",
"O filme que assisti ontem foi ótimo.",
"Preciso resolver esse problema o mais rápido possível.",
"Adoro explorar novos lugares.",
"Vou visitar meus avós no domingo.",
"Estou ansioso para as férias de verão.",
"Gosto de fazer caminhadas na natureza.",
"O restaurante tem uma vista incrível.",
"Vamos sair para jantar no sábado.",
]

A "amostras" de texto precisa ser "transformada" em <b>padrões</b>

<p>Um padrão é um conjunto de características, geralmente representado por um vetor e um conjunto de padrões no formato de tabela. Onde cada linha é um padrão e as colunas as características e, geralmente, na última coluna a <b>classe</b></p>

In [41]:
import random

pre_padroes = []
for frase in ingles:
  pre_padroes.append( [frase, 'inglês'])

for frase in espanhol:
  pre_padroes.append( [frase, 'espanhol'])

for frase in portugues:
  pre_padroes.append( [frase, 'português'])

random.shuffle(pre_padroes)
print(pre_padroes)

[['El clima está agradable hoy.', 'espanhol'], ['Estoy planeando unas vacaciones.', 'espanhol'], ['I need to buy some groceries.', 'inglês'], ['A festa começa às 20h.', 'português'], ['Can you help me with this?', 'inglês'], ['Necesito comprar algunas frutas.', 'espanhol'], ['Do you have any recommendations for restaurants?', 'inglês'], ['Tengo una reunión a las 2 PM.', 'espanhol'], ['Estou indo para o trabalho agora.', 'português'], ['Me gustaría ir de vacaciones.', 'espanhol'], ['Estou aprendendo a cozinhar pratos novos.', 'português'], ['Gosto de praticar esportes ao ar livre.', 'português'], ['Me gusta cocinar la cena en casa.', 'espanhol'], ['Gosto de ouvir música clássica.', 'português'], ['Vou visitar meus avós no domingo.', 'português'], ['Vamos fazer um churrasco no final de semana.', 'português'], ['Vou viajar para o exterior nas férias.', 'português'], ['Have a great day!', 'inglês'], ['O restaurante tem uma vista incrível.', 'português'], ['Preciso comprar leite e pão.', 'p

O DataFrame do pandas facilita a visualização.

In [42]:
import pandas as pd
dados = pd.DataFrame(pre_padroes)
dados

0          1
0           El clima está agradable hoy.   espanhol
1       Estoy planeando unas vacaciones.   espanhol
2          I need to buy some groceries.     inglês
3                 A festa começa às 20h.  português
4             Can you help me with this?     inglês
..                                   ...        ...
87  O filme que assisti ontem foi ótimo.  português
88                  Let's go for a walk.     inglês
89     Vamos sair para jantar no sábado.  português
90         Adoro explorar novos lugares.  português
91             Quiero aprender italiano.   espanhol

[92 rows x 2 columns]

<h1>Construção dos atributos</h1>
<p>Esse é o coração desse trabalho e que deverá ser desenvolvido por vocês. Pensem em como podemos "medir" cadas frase/sentença e extrair características que melhorem o resultado do processo de identificação.<p>
<p>Após a criação de cada novo atributo, execute as etapas seguintes e registre as métricas da matriz de confusão. Principalmente acurácia e a precisão.</p>

In [43]:
# a entrada é o vetor pre_padroes e a saída desse passo deverá ser "padrões"
import re, collections
import spacy

nlp_en = spacy.blank('en')
nlp_es = spacy.blank('es')
nlp_pt = spacy.blank('pt')

stopwords_en = nlp_en.Defaults.stop_words
stopwords_es = nlp_es.Defaults.stop_words
stopwords_pt = nlp_pt.Defaults.stop_words

print('Inglês:', list(stopwords_en)[:10])
print('Espanhol:', list(stopwords_es)[:10])
print('Português:', list(stopwords_pt)[:10])

def tamanhoMedioFrases(texto):
  palavras = re.split("\s",texto)
  #print(palavras)
  tamanhos = [len(s) for s in palavras if len(s)>0]
  #print(tamanhos)
  soma = 0
  for t in tamanhos:
    soma=soma+t
  return soma / len(tamanhos)

def contaStopwords(texto):
    palavras = re.findall(r'\w+', texto.lower())
    n_en = sum(1 for w in palavras if w in stopwords_en)
    n_es = sum(1 for w in palavras if w in stopwords_es)
    n_pt = sum(1 for w in palavras if w in stopwords_pt)
    return n_en, n_es, n_pt

def ratio_acentos(texto: str) -> float:
    ACENTOS = "áéíóúàèìòùãõâêîôûçñ"
    letras = [char for char in texto.lower() if char.isalpha()]
    if not letras:
        return 0.0
    total_acentos = sum(1 for char in letras if char in ACENTOS)
    return total_acentos / len(letras)

def conta_ntil(texto):
    # Conta quantas ocorrências de 'ñ' no texto. Feature para sinalizar espanhol.
    return texto.lower().count('ñ')

def bigramas(texto):
    # 1. Normaliza minúsculas e sem espaços
    normalized = re.sub(r'\s+', '', texto.lower())
    # 2. Extrai todos os pares de caracteres adjacentes
    return [normalized[i : i + 2] for i in range(len(normalized) - 1)]

def extraiCaracteristicas(frase):
    texto = frase[0]
    pattern_regex = re.compile('[^\w+]', re.UNICODE)
    texto = re.sub(pattern_regex,' ',texto)

    tm_frases = tamanhoMedioFrases(texto)
    n_en, n_es, n_pt = contaStopwords(texto)

    acentos = ratio_acentos(texto)
    ntil = conta_ntil(texto)

    bigrams = bigramas(texto)
    bigram_counts = collections.Counter(bigrams)
    freq_th = bigram_counts['th'] # típico de inglês
    freq_ão = bigram_counts['ão'] # típico de português
    freq_ll = bigram_counts['ll'] # típico de espanhol

    caracteristica1 = tm_frases
    caracteristica2 = n_en
    caracteristica3 = n_es
    caracteristica4 = n_pt
    caracteristica5 = acentos
    caracteristica6 = ntil
    caracteristica7 = freq_th
    caracteristica8 = freq_ão
    caracteristica9 = freq_ll

    padrao = [caracteristica1, caracteristica2, caracteristica3, caracteristica4, caracteristica5, caracteristica6, caracteristica7, caracteristica8, caracteristica9, frase[1]]
    return padrao

def geraPadroes(frases):
  padroes = []
  for frase in frases:
    padrao = extraiCaracteristicas(frase)
    padroes.append(padrao)
  return padroes

# converte o formato [frase classe] em
# [caracteristica_1, caracteristica_2,... caracteristica n, classe]
padroes = geraPadroes(pre_padroes)

#
# apenas para visualizacao
print(padroes)

dados = pd.DataFrame(padroes)
dados

Inglês: ['my', 'ours', 'myself', 'nowhere', 'whole', 'well', 'enough', 'wherever', 'make', 'besides']
Espanhol: ['tuyas', 'desde', 'ya', 'mal', 'diferente', 'estará', 'vuestros', 'tambien', 'cierta', 'apenas']
Português: ['desde', 'novas', 'mal', 'qualquer', 'dezassete', 'estará', 'apenas', 'fazer', 'muitos', 'alguns']
[[4.6, 0, 3, 1, 0.043478260869565216, 0, 0, 0, 0, 'espanhol'], [7.0, 0, 2, 0, 0.0, 0, 0, 0, 0, 'espanhol'], [3.8333333333333335, 3, 0, 0, 0.0, 0, 0, 0, 0, 'inglês'], [3.4, 1, 1, 2, 0.13333333333333333, 0, 0, 0, 0, 'português'], [3.3333333333333335, 5, 1, 1, 0.0, 0, 2, 0, 0, 'inglês'], [7.0, 0, 1, 0, 0.0, 0, 0, 0, 0, 'espanhol'], [5.857142857142857, 5, 0, 2, 0.0, 0, 0, 0, 0, 'inglês'], [3.142857142857143, 1, 4, 1, 0.047619047619047616, 0, 0, 0, 0, 'espanhol'], [4.5, 0, 2, 4, 0.0, 0, 0, 0, 0, 'português'], [4.8, 1, 3, 3, 0.041666666666666664, 0, 0, 0, 0, 'espanhol'], [5.833333333333333, 1, 1, 3, 0.0, 0, 0, 0, 0, 'português'], [4.571428571428571, 0, 1, 2, 0.0, 0, 0, 0, 0, '

0  1  2  3         4  5  6  7  8          9
0   4.600000  0  3  1  0.043478  0  0  0  0   espanhol
1   7.000000  0  2  0  0.000000  0  0  0  0   espanhol
2   3.833333  3  0  0  0.000000  0  0  0  0     inglês
3   3.400000  1  1  2  0.133333  0  0  0  0  português
4   3.333333  5  1  1  0.000000  0  2  0  0     inglês
..       ... .. .. ..       ... .. .. .. ..        ...
87  4.142857  0  2  4  0.034483  0  0  0  0  português
88  2.333333  3  1  2  0.000000  0  0  0  0     inglês
89  4.500000  1  3  2  0.037037  0  0  0  0  português
90  6.250000  0  0  1  0.000000  0  0  0  0  português
91  7.333333  0  0  0  0.000000  0  0  0  0   espanhol

[92 rows x 10 columns]

<h2>Treinando o modelo com SVM</h1>
<p>Separando o conjunto de treinamento do conjunto de testes</p>

In [44]:
from sklearn.model_selection import train_test_split
import numpy as np


#from sklearn.metrics import confusion_matrix

vet = np.array(padroes)
classes = vet[:,-1]         # classes = [p[-1] for p in padroes]
#print(classes)
padroes_sem_classe = vet[:,0:-1]
#print(padroes_sem_classe)
X_train, X_test, y_train, y_test = train_test_split(padroes_sem_classe, classes, test_size=0.25, stratify=classes)


Com os conjuntos separados, podemos "treinar" o modelo usando a SVM.

In [45]:
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import time
treinador = svm.SVC()  #algoritmo escolhido
modelo = treinador.fit(X_train, y_train)

arquivo_resultado = 'resultado' + str( int(time.time())) + '.txt'

#
# score com os dados de treinamento
acuracia = modelo.score(X_train, y_train)
print("Acurácia nos dados de treinamento: {:.2f}%".format(acuracia * 100))

#
# melhor avaliar com a matriz de confusão
y_pred = modelo.predict(X_train)
cm = confusion_matrix(y_train, y_pred)
print(cm)
print(classification_report(y_train, y_pred))

#
# com dados de teste que não foram usados no treinamento
print('métricas mais confiáveis')
y_pred2 = modelo.predict(X_test)
cm = confusion_matrix(y_test, y_pred2)
print(cm)
print(classification_report(y_test, y_pred2))


with open(arquivo_resultado, 'w') as f:
    f.write("Acurácia nos dados de treinamento: {:.2f}%\n".format(acuracia * 100))
    f.write("Matriz de confusão (dados de treinamento):\n")
    f.write(str(cm) + "\n")
    f.write("Relatório de classificação (dados de treinamento):\n")
    f.write(classification_report(y_train, y_pred) + "\n")

    f.write("Matriz de confusão (dados de teste):\n")
    f.write(str(confusion_matrix(y_test, y_pred2)) + "\n")
    f.write("Relatório de classificação (dados de teste):\n")
    f.write(classification_report(y_test, y_pred2) + "\n")
print(f"Resultados salvos em {arquivo_resultado}")


Acurácia nos dados de treinamento: 94.20%
[[21  0  1]
 [ 0 23  0]
 [ 3  0 21]]
              precision    recall  f1-score   support

    espanhol       0.88      0.95      0.91        22
      inglês       1.00      1.00      1.00        23
   português       0.95      0.88      0.91        24

    accuracy                           0.94        69
   macro avg       0.94      0.94      0.94        69
weighted avg       0.94      0.94      0.94        69

métricas mais confiáveis
[[7 0 1]
 [1 6 0]
 [1 0 7]]
              precision    recall  f1-score   support

    espanhol       0.78      0.88      0.82         8
      inglês       1.00      0.86      0.92         7
   português       0.88      0.88      0.88         8

    accuracy                           0.87        23
   macro avg       0.88      0.87      0.87        23
weighted avg       0.88      0.87      0.87        23

Resultados salvos em resultado1750145290.txt
