<h1>Identificador automático de idioma</h1>
<p><b>Problema</b>: Dados um texto de entrada, é possível identificar em qual língua o texto está escrito?</p>
<p>
Entrada: "texto qualquer" <br />
Saída: português ou inglês ou francês ou italiano ou...
</p>
<p>&nbsp;</p>

<h2>O processo de Reconhecimento de Padrões</h2>
<p>O objetivo desse trabalho é demonstrar o processo de "construção de atributos" e como ele é fundamental para o <b>Reconhecimento de Padrões (RP)</b>.</p>

<p>Primeiro um conjunto de "amostras" previamente conhecido (classificado)</p>

In [57]:
#
# amostras de texto em diferentes línguas
#
ingles = [
"Hello, how are you?",
"I love to read books.",
"The weather is nice today.",
"Where is the nearest restaurant?",
"What time is it?",
"I enjoy playing soccer.",
"Can you help me with this?",
"I'm going to the movies tonight.",
"This is a beautiful place.",
"I like listening to music.",
"Do you speak English?",
"What is your favorite color?",
"I'm learning to play the guitar.",
"Have a great day!",
"I need to buy some groceries.",
"Let's go for a walk.",
"How was your weekend?",
"I'm excited for the concert.",
"Could you pass me the salt, please?",
"I have a meeting at 2 PM.",
"I'm planning a vacation.",
"She sings beautifully.",
"The cat is sleeping.",
"I want to learn French.",
"I enjoy going to the beach.",
"Where can I find a taxi?",
"I'm sorry for the inconvenience.",
"I'm studying for my exams.",
"I like to cook dinner at home.",
"Do you have any recommendations for restaurants?",
]

espanhol = [
"Hola, ¿cómo estás?",
"Me encanta leer libros.",
"El clima está agradable hoy.",
"¿Dónde está el restaurante más cercano?",
"¿Qué hora es?",
"Voy al parque todos los días.",
"¿Puedes ayudarme con esto?",
"Me gustaría ir de vacaciones.",
"Este es mi libro favorito.",
"Me gusta bailar salsa.",
"¿Hablas español?",
"¿Cuál es tu comida favorita?",
"Estoy aprendiendo a tocar el piano.",
"¡Que tengas un buen día!",
"Necesito comprar algunas frutas.",
"Vamos a dar un paseo.",
"¿Cómo estuvo tu fin de semana?",
"Estoy emocionado por el concierto.",
"¿Me pasas la sal, por favor?",
"Tengo una reunión a las 2 PM.",
"Estoy planeando unas vacaciones.",
"Ella canta hermosamente.",
"El perro está jugando.",
"Quiero aprender italiano.",
"Disfruto ir a la playa.",
"¿Dónde puedo encontrar un taxi?",
"Lamento las molestias.",
"Estoy estudiando para mis exámenes.",
"Me gusta cocinar la cena en casa.",
"¿Tienes alguna recomendación de restaurantes?",
]

portugues = [
"Estou indo para o trabalho agora.",
"Adoro passar tempo com minha família.",
"Preciso comprar leite e pão.",
"Vamos ao cinema no sábado.",
"Gosto de praticar esportes ao ar livre.",
"O trânsito está terrível hoje.",
"A comida estava deliciosa!",
"Você já visitou o Rio de Janeiro?",
"Tenho uma reunião importante amanhã.",
"A festa começa às 20h.",
"Estou cansado depois de um longo dia de trabalho.",
"Vamos fazer um churrasco no final de semana.",
"O livro que estou lendo é muito interessante.",
"Estou aprendendo a cozinhar pratos novos.",
"Preciso fazer exercícios físicos regularmente.",
"Vou viajar para o exterior nas férias.",
"Você gosta de dançar?",
"Hoje é meu aniversário!",
"Gosto de ouvir música clássica.",
"Estou estudando para o vestibular.",
"Meu time de futebol favorito ganhou o jogo.",
"Quero aprender a tocar violão.",
"Vamos fazer uma viagem de carro.",
"O parque fica cheio aos finais de semana.",
"O filme que assisti ontem foi ótimo.",
"Preciso resolver esse problema o mais rápido possível.",
"Adoro explorar novos lugares.",
"Vou visitar meus avós no domingo.",
"Estou ansioso para as férias de verão.",
"Gosto de fazer caminhadas na natureza.",
"O restaurante tem uma vista incrível.",
"Vamos sair para jantar no sábado.",
]

A "amostras" de texto precisa ser "transformada" em <b>padrões</b>

<p>Um padrão é um conjunto de características, geralmente representado por um vetor e um conjunto de padrões no formato de tabela. Onde cada linha é um padrão e as colunas as características e, geralmente, na última coluna a <b>classe</b></p>

In [58]:
import random

pre_padroes = []
for frase in ingles:
  pre_padroes.append( [frase, 'inglês'])

for frase in espanhol:
  pre_padroes.append( [frase, 'espanhol'])

for frase in portugues:
  pre_padroes.append( [frase, 'português'])

random.shuffle(pre_padroes)
print(pre_padroes)

[['Me gusta cocinar la cena en casa.', 'espanhol'], ['Gosto de praticar esportes ao ar livre.', 'português'], ['Voy al parque todos los días.', 'espanhol'], ['Have a great day!', 'inglês'], ['Preciso comprar leite e pão.', 'português'], ['Quiero aprender italiano.', 'espanhol'], ['Vamos a dar un paseo.', 'espanhol'], ["I'm planning a vacation.", 'inglês'], ['I enjoy going to the beach.', 'inglês'], ["I'm excited for the concert.", 'inglês'], ['Me gusta bailar salsa.', 'espanhol'], ['Me gustaría ir de vacaciones.', 'espanhol'], ['Lamento las molestias.', 'espanhol'], ['¿Cómo estuvo tu fin de semana?', 'espanhol'], ['She sings beautifully.', 'inglês'], ['¿Qué hora es?', 'espanhol'], ['Estoy planeando unas vacaciones.', 'espanhol'], ['Você gosta de dançar?', 'português'], ['Vou visitar meus avós no domingo.', 'português'], ['Vamos fazer um churrasco no final de semana.', 'português'], ['Hello, how are you?', 'inglês'], ['Ella canta hermosamente.', 'espanhol'], ['¿Tienes alguna recomendaci

O DataFrame do pandas facilita a visualização.

In [59]:
import pandas as pd
dados = pd.DataFrame(pre_padroes)
dados

0          1
0           Me gusta cocinar la cena en casa.   espanhol
1     Gosto de praticar esportes ao ar livre.  português
2               Voy al parque todos los días.   espanhol
3                           Have a great day!     inglês
4                Preciso comprar leite e pão.  português
..                                        ...        ...
87             Quero aprender a tocar violão.  português
88            Gosto de ouvir música clássica.  português
89                       The cat is sleeping.     inglês
90               ¿Me pasas la sal, por favor?   espanhol
91  Estou aprendendo a cozinhar pratos novos.  português

[92 rows x 2 columns]

<h1>Construção dos atributos</h1>
<p>Esse é o coração desse trabalho e que deverá ser desenvolvido por vocês. Pensem em como podemos "medir" cadas frase/sentença e extrair características que melhorem o resultado do processo de identificação.<p>
<p>Após a criação de cada novo atributo, execute as etapas seguintes e registre as métricas da matriz de confusão. Principalmente acurácia e a precisão.</p>

In [60]:
import spacy

nlp_en = spacy.blank('en')
nlp_es = spacy.blank('es')
nlp_pt = spacy.blank('pt')

stopwords_en = nlp_en.Defaults.stop_words
stopwords_es = nlp_es.Defaults.stop_words
stopwords_pt = nlp_pt.Defaults.stop_words


In [61]:
# a entrada é o vetor pre_padroes e a saída desse passo deverá ser "padrões"
import re

print('Inglês:', list(stopwords_en)[:10])
print('Espanhol:', list(stopwords_es)[:10])
print('Português:', list(stopwords_pt)[:10])
def tamanhoMedioFrases(texto):
  palavras = re.split("\s",texto)
  #print(palavras)
  tamanhos = [len(s) for s in palavras if len(s)>0]
  #print(tamanhos)
  soma = 0
  for t in tamanhos:
    soma=soma+t
  return soma / len(tamanhos)


def contaStopwords(texto):
    palavras = re.findall(r'\w+', texto.lower())
    n_en = sum(1 for w in palavras if w in stopwords_en)
    n_es = sum(1 for w in palavras if w in stopwords_es)
    n_pt = sum(1 for w in palavras if w in stopwords_pt)
    return n_en, n_es, n_pt

def extraiCaracteristicas(frase):
    texto = frase[0]
    pattern_regex = re.compile('[^\w+]', re.UNICODE)
    texto = re.sub(pattern_regex,' ',texto)
    caracteristica1 = tamanhoMedioFrases(texto)
    n_en, n_es, n_pt = contaStopwords(texto)
    caracteristica2 = n_en
    caracteristica3 = n_es
    caracteristica4 = n_pt
    padrao = [caracteristica1, caracteristica2, caracteristica3, caracteristica4, frase[1]]
    return padrao

def geraPadroes(frases):
  padroes = []
  for frase in frases:
    padrao = extraiCaracteristicas(frase)
    padroes.append(padrao)
  return padroes

# converte o formato [frase classe] em
# [caracteristica_1, caracteristica_2,... caracteristica n, classe]
padroes = geraPadroes(pre_padroes)

#
# apenas para visualizacao
print(padroes)

dados = pd.DataFrame(padroes)
dados

Inglês: ['both', 'that', 'sometime', 'than', 'used', 'whatever', 'beside', "'ve", '‘re', 'own']
Espanhol: ['tarde', 'podría', 'varios', 'vez', 'fueron', 'serán', 'sobre', 'podriais', 'nada', 'yo']
Português: ['tarde', 'somente', 'diante', 'vós', 'treze', 'vez', 'faz', 'questão', 'sobre', 'meu']
[[3.7142857142857144, 1, 3, 1, 'espanhol'], [4.571428571428571, 0, 1, 2, 'português'], [3.8333333333333335, 0, 5, 1, 'espanhol'], [3.25, 2, 1, 1, 'inglês'], [4.6, 0, 1, 1, 'português'], [7.333333333333333, 0, 0, 0, 'espanhol'], [3.2, 1, 4, 2, 'espanhol'], [3.8, 2, 1, 1, 'inglês'], [3.5, 3, 0, 0, 'inglês'], [3.6666666666666665, 3, 0, 1, 'inglês'], [4.5, 1, 1, 1, 'espanhol'], [4.8, 1, 3, 3, 'espanhol'], [6.333333333333333, 0, 1, 0, 'espanhol'], [3.8333333333333335, 0, 5, 2, 'espanhol'], [6.333333333333333, 1, 0, 0, 'inglês'], [3.0, 0, 2, 0, 'espanhol'], [7.0, 0, 2, 0, 'espanhol'], [4.25, 0, 1, 2, 'português'], [4.5, 1, 1, 2, 'português'], [4.5, 1, 4, 5, 'português'], [3.5, 3, 0, 0, 'inglês'], [7.0

<>:8: SyntaxWarning: invalid escape sequence '\s'
<>:27: SyntaxWarning: invalid escape sequence '\w'
<>:8: SyntaxWarning: invalid escape sequence '\s'
<>:27: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_64495/1181207944.py:8: SyntaxWarning: invalid escape sequence '\s'
  palavras = re.split("\s",texto)
/tmp/ipykernel_64495/1181207944.py:27: SyntaxWarning: invalid escape sequence '\w'
  pattern_regex = re.compile('[^\w+]', re.UNICODE)


0  1  2  3          4
0   3.714286  1  3  1   espanhol
1   4.571429  0  1  2  português
2   3.833333  0  5  1   espanhol
3   3.250000  2  1  1     inglês
4   4.600000  0  1  1  português
..       ... .. .. ..        ...
87  5.000000  1  1  2  português
88  5.200000  0  1  1  português
89  4.000000  2  0  0     inglês
90  3.333333  1  3  3   espanhol
91  5.833333  1  1  3  português

[92 rows x 5 columns]

<h2>Treinando o modelo com SVM</h1>
<p>Separando o conjunto de treinamento do conjunto de testes</p>

In [62]:
from sklearn.model_selection import train_test_split
import numpy as np


#from sklearn.metrics import confusion_matrix

vet = np.array(padroes)
classes = vet[:,-1]         # classes = [p[-1] for p in padroes]
#print(classes)
padroes_sem_classe = vet[:,0:-1]
#print(padroes_sem_classe)
X_train, X_test, y_train, y_test = train_test_split(padroes_sem_classe, classes, test_size=0.25, stratify=classes)


Com os conjuntos separados, podemos "treinar" o modelo usando a SVM.

In [63]:
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import time
treinador = svm.SVC()  #algoritmo escolhido
modelo = treinador.fit(X_train, y_train)

arquivo_resultado = 'resultado' + str( int(time.time())) + '.txt'

#
# score com os dados de treinamento
acuracia = modelo.score(X_train, y_train)
print("Acurácia nos dados de treinamento: {:.2f}%".format(acuracia * 100))

#
# melhor avaliar com a matriz de confusão
y_pred = modelo.predict(X_train)
cm = confusion_matrix(y_train, y_pred)
print(cm)
print(classification_report(y_train, y_pred))

#
# com dados de teste que não foram usados no treinamento
print('métricas mais confiáveis')
y_pred2 = modelo.predict(X_test)
cm = confusion_matrix(y_test, y_pred2)
print(cm)
print(classification_report(y_test, y_pred2))


with open(arquivo_resultado, 'w') as f:
    f.write("Acurácia nos dados de treinamento: {:.2f}%\n".format(acuracia * 100))
    f.write("Matriz de confusão (dados de treinamento):\n")
    f.write(str(cm) + "\n")
    f.write("Relatório de classificação (dados de treinamento):\n")
    f.write(classification_report(y_train, y_pred) + "\n")

    f.write("Matriz de confusão (dados de teste):\n")
    f.write(str(confusion_matrix(y_test, y_pred2)) + "\n")
    f.write("Relatório de classificação (dados de teste):\n")
    f.write(classification_report(y_test, y_pred2) + "\n")
print(f"Resultados salvos em {arquivo_resultado}")


Acurácia nos dados de treinamento: 91.30%
[[22  0  1]
 [ 1 21  0]
 [ 4  0 20]]
              precision    recall  f1-score   support

    espanhol       0.81      0.96      0.88        23
      inglês       1.00      0.95      0.98        22
   português       0.95      0.83      0.89        24

    accuracy                           0.91        69
   macro avg       0.92      0.91      0.92        69
weighted avg       0.92      0.91      0.91        69

métricas mais confiáveis
[[6 0 1]
 [0 8 0]
 [0 0 8]]
              precision    recall  f1-score   support

    espanhol       1.00      0.86      0.92         7
      inglês       1.00      1.00      1.00         8
   português       0.89      1.00      0.94         8

    accuracy                           0.96        23
   macro avg       0.96      0.95      0.95        23
weighted avg       0.96      0.96      0.96        23

Resultados salvos em resultado1749670495.txt
